---
packageConfigs:
  "github.com/kujilabo/cocotola-1.21/cocotola-core/src/app/domain":
    forbiddenPackages:
      - net/http
      - database/sql
      - gorm.io/gorm
      - github.com/foo/bar/repository
  "github.com/kujilabo/cocotola-1.21/cocotola-core/src/app/service":
    forbiddenPackages:
      - github.com/foo/bar/repository
      - "net/http"
  "main":
    forbiddenPackages:

debug: false
