---
steps:
  # - name: 'gcr.io/cloud-builders/bazel'
  #   entrypoint: 'bazel'
  #   args: ['version']
  # - name: 'gcr.io/cloud-builders/bazel'
  #   entrypoint: 'bazel'
  #   args: ['build', '//...']steps:
  - name: 'gcr.io/cloud-marketplace-containers/google/bazel'
    entrypoint: 'bazel'
    args: ['build', '//cocotola-api/src:tarball']
