---
app:
  name: cocotola-app
  httpPort: 8080
  metricsPort: 8081
db:
  driverName: postgres
  postgres:
    username: $POSTGRES_USERNAME
    password: $POSTGRES_PASSWORD
    host: $POSTGRES_HOST
    port: $POSTGRES_PORT
    database: $POSTGRES_DATABASE
auth:
  signingKey: $SIGNING_KEY
  accessTokenTtlMin: 30
  refreshTokenTtlHour: 720
  googleCallbackUrl: https://www.cocotola.com/app/callback
  googleClientId: 830416463276-lf7d9r39v1ct78u6p1dke6cv5kd8g6o1.apps.googleusercontent.com
  googleClientSecret: $GOOGLE_CLIENT_SECRET
  apiTimeoutSec: 5
trace:
  exporter: none
cors:
  allowOrigins:
    - "https://www.cocotola.com"
shutdown:
  timeSec1: 10
  timeSec2: 10
log:
  level:
    default: debug
    cocotola-app: $LOG_LEVEL
swagger:
  enabled: false
  host: localhost:8080
  schema: http
debug:
  gin: false
  wait: false
