---
app:
  name: golang-structure
  httpPort: 8000
  metricsPort: 8001
db:
#   driverName: sqlite3
#   sqlite3:
#     file: app.db
  driverName: postgres
  migration: true
  mysql:
    username: user
    password: password
    host: 127.0.0.1
    port: 3306
    database: development
  postgres:
    username: user
    password: password
    host: 127.0.0.1
    port: 5432
    database: postgres
authApi:
  endpoint: http://localhost:8080/api/auth
  username: $AUTH_API_USERNAME
  password: $AUTH_API_PASSWORD
auth:
  signingKey: ah5T9Y9V2JPU74fhCtHQfDqLp3Zg8ZNc
  accessTokenTtlMin: 5
  refreshTokenTtlHour: 720
  googleCallbackUrl: http://localhost:5173/app/callback
  googleClientId: 830416463276-3ts1rsinahi0hdnsfc10m6mabpttrd5i.apps.googleusercontent.com
  googleClientSecret: $GOOGLE_CLIENT_SECRET
  apiTimeoutSec: 5
trace:
  # exporter: jaeger
  exporter: otlp
  otlp:
    endpoint: localhost:4318
    insecure: true
cors:
  allowOrigins:
    - "*"
shutdown:
  timeSec1: 1
  timeSec2: 1
log:
  level:
    default: debug
    cocotola-core: debug
swagger:
  enabled: true
  host: localhost:8080
  schema: http
debug:
  ginMode: true
  # wait: true
