---
with-expecter: true

mockname: "{{.InterfaceName}}"
outpkg: mocks
filename: "{{.MockName}}.go"
packages:
  github.com/kujilabo/cocotola-1.21/cocotola-auth/src/controller/gin:
    config:
      dir: src/controller/gin/mocks
    interfaces:
      AuthenticationUsecaseInterface:
      GoogleUserUsecaseInterface:
