# fly.toml app configuration file generated for cocotola on 2024-01-11T23:07:21+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cocotola"
primary_region = "nrt"

# [build]

[build]
builder = "paketobuildpacks/builder:base"
buildpacks = ["gcr.io/paketo-buildpacks/go"]

[build.args]
BP_GO_TARGETS = "./src"

[env]
PORT = "8080"
APP_ENV = "production"
LOG_LEVEL = "info"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
