// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kujilabo/cocotola-1.21/cocotola-core/src/domain"

	mock "github.com/stretchr/testify/mock"

	service "github.com/kujilabo/cocotola-1.21/cocotola-core/src/service"

	workbookadddomain "github.com/kujilabo/cocotola-1.21/cocotola-core/src/domain/workbookadd"
)

// WorkbookCommandUsecase is an autogenerated mock type for the WorkbookCommandUsecase type
type WorkbookCommandUsecase struct {
	mock.Mock
}

type WorkbookCommandUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkbookCommandUsecase) EXPECT() *WorkbookCommandUsecase_Expecter {
	return &WorkbookCommandUsecase_Expecter{mock: &_m.Mock}
}

// AddWorkbook provides a mock function with given fields: ctx, operator, param
func (_m *WorkbookCommandUsecase) AddWorkbook(ctx context.Context, operator service.OperatorInterface, param *workbookadddomain.Parameter) (*domain.WorkbookID, error) {
	ret := _m.Called(ctx, operator, param)

	var r0 *domain.WorkbookID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.OperatorInterface, *workbookadddomain.Parameter) (*domain.WorkbookID, error)); ok {
		return rf(ctx, operator, param)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.OperatorInterface, *workbookadddomain.Parameter) *domain.WorkbookID); ok {
		r0 = rf(ctx, operator, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WorkbookID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.OperatorInterface, *workbookadddomain.Parameter) error); ok {
		r1 = rf(ctx, operator, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkbookCommandUsecase_AddWorkbook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWorkbook'
type WorkbookCommandUsecase_AddWorkbook_Call struct {
	*mock.Call
}

// AddWorkbook is a helper method to define mock.On call
//   - ctx context.Context
//   - operator service.OperatorInterface
//   - param *workbookadddomain.Parameter
func (_e *WorkbookCommandUsecase_Expecter) AddWorkbook(ctx interface{}, operator interface{}, param interface{}) *WorkbookCommandUsecase_AddWorkbook_Call {
	return &WorkbookCommandUsecase_AddWorkbook_Call{Call: _e.mock.On("AddWorkbook", ctx, operator, param)}
}

func (_c *WorkbookCommandUsecase_AddWorkbook_Call) Run(run func(ctx context.Context, operator service.OperatorInterface, param *workbookadddomain.Parameter)) *WorkbookCommandUsecase_AddWorkbook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.OperatorInterface), args[2].(*workbookadddomain.Parameter))
	})
	return _c
}

func (_c *WorkbookCommandUsecase_AddWorkbook_Call) Return(_a0 *domain.WorkbookID, _a1 error) *WorkbookCommandUsecase_AddWorkbook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WorkbookCommandUsecase_AddWorkbook_Call) RunAndReturn(run func(context.Context, service.OperatorInterface, *workbookadddomain.Parameter) (*domain.WorkbookID, error)) *WorkbookCommandUsecase_AddWorkbook_Call {
	_c.Call.Return(run)
	return _c
}

// NewWorkbookCommandUsecase creates a new instance of WorkbookCommandUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkbookCommandUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkbookCommandUsecase {
	mock := &WorkbookCommandUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
