// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kujilabo/redstart/user/domain"

	mock "github.com/stretchr/testify/mock"

	student "github.com/kujilabo/cocotola-1.21/cocotola-core/src/usecase/student"

	workbookfind "github.com/kujilabo/cocotola-1.21/cocotola-core/src/domain/workbookfind"
)

// WorkbookUsecaseInterface is an autogenerated mock type for the WorkbookUsecaseInterface type
type WorkbookUsecaseInterface struct {
	mock.Mock
}

type WorkbookUsecaseInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkbookUsecaseInterface) EXPECT() *WorkbookUsecaseInterface_Expecter {
	return &WorkbookUsecaseInterface_Expecter{mock: &_m.Mock}
}

// FindWorkbooks provides a mock function with given fields: ctx, organizationID, operatorID, param
func (_m *WorkbookUsecaseInterface) FindWorkbooks(ctx context.Context, organizationID *domain.OrganizationID, operatorID *domain.AppUserID, param *workbookfind.Parameter) (*workbookfind.Result, error) {
	ret := _m.Called(ctx, organizationID, operatorID, param)

	var r0 *workbookfind.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.OrganizationID, *domain.AppUserID, *workbookfind.Parameter) (*workbookfind.Result, error)); ok {
		return rf(ctx, organizationID, operatorID, param)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.OrganizationID, *domain.AppUserID, *workbookfind.Parameter) *workbookfind.Result); ok {
		r0 = rf(ctx, organizationID, operatorID, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workbookfind.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.OrganizationID, *domain.AppUserID, *workbookfind.Parameter) error); ok {
		r1 = rf(ctx, organizationID, operatorID, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkbookUsecaseInterface_FindWorkbooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindWorkbooks'
type WorkbookUsecaseInterface_FindWorkbooks_Call struct {
	*mock.Call
}

// FindWorkbooks is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID *domain.OrganizationID
//   - operatorID *domain.AppUserID
//   - param *workbookfind.Parameter
func (_e *WorkbookUsecaseInterface_Expecter) FindWorkbooks(ctx interface{}, organizationID interface{}, operatorID interface{}, param interface{}) *WorkbookUsecaseInterface_FindWorkbooks_Call {
	return &WorkbookUsecaseInterface_FindWorkbooks_Call{Call: _e.mock.On("FindWorkbooks", ctx, organizationID, operatorID, param)}
}

func (_c *WorkbookUsecaseInterface_FindWorkbooks_Call) Run(run func(ctx context.Context, organizationID *domain.OrganizationID, operatorID *domain.AppUserID, param *workbookfind.Parameter)) *WorkbookUsecaseInterface_FindWorkbooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.OrganizationID), args[2].(*domain.AppUserID), args[3].(*workbookfind.Parameter))
	})
	return _c
}

func (_c *WorkbookUsecaseInterface_FindWorkbooks_Call) Return(_a0 *workbookfind.Result, _a1 error) *WorkbookUsecaseInterface_FindWorkbooks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WorkbookUsecaseInterface_FindWorkbooks_Call) RunAndReturn(run func(context.Context, *domain.OrganizationID, *domain.AppUserID, *workbookfind.Parameter) (*workbookfind.Result, error)) *WorkbookUsecaseInterface_FindWorkbooks_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveWorkbookByID provides a mock function with given fields: ctx, organizationID, operatorID, workbookID
func (_m *WorkbookUsecaseInterface) RetrieveWorkbookByID(ctx context.Context, organizationID *domain.OrganizationID, operatorID *domain.AppUserID, workbookID int) (*student.WorkbookRetrieveModel, error) {
	ret := _m.Called(ctx, organizationID, operatorID, workbookID)

	var r0 *student.WorkbookRetrieveModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.OrganizationID, *domain.AppUserID, int) (*student.WorkbookRetrieveModel, error)); ok {
		return rf(ctx, organizationID, operatorID, workbookID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.OrganizationID, *domain.AppUserID, int) *student.WorkbookRetrieveModel); ok {
		r0 = rf(ctx, organizationID, operatorID, workbookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*student.WorkbookRetrieveModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.OrganizationID, *domain.AppUserID, int) error); ok {
		r1 = rf(ctx, organizationID, operatorID, workbookID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkbookUsecaseInterface_RetrieveWorkbookByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveWorkbookByID'
type WorkbookUsecaseInterface_RetrieveWorkbookByID_Call struct {
	*mock.Call
}

// RetrieveWorkbookByID is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID *domain.OrganizationID
//   - operatorID *domain.AppUserID
//   - workbookID int
func (_e *WorkbookUsecaseInterface_Expecter) RetrieveWorkbookByID(ctx interface{}, organizationID interface{}, operatorID interface{}, workbookID interface{}) *WorkbookUsecaseInterface_RetrieveWorkbookByID_Call {
	return &WorkbookUsecaseInterface_RetrieveWorkbookByID_Call{Call: _e.mock.On("RetrieveWorkbookByID", ctx, organizationID, operatorID, workbookID)}
}

func (_c *WorkbookUsecaseInterface_RetrieveWorkbookByID_Call) Run(run func(ctx context.Context, organizationID *domain.OrganizationID, operatorID *domain.AppUserID, workbookID int)) *WorkbookUsecaseInterface_RetrieveWorkbookByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.OrganizationID), args[2].(*domain.AppUserID), args[3].(int))
	})
	return _c
}

func (_c *WorkbookUsecaseInterface_RetrieveWorkbookByID_Call) Return(_a0 *student.WorkbookRetrieveModel, _a1 error) *WorkbookUsecaseInterface_RetrieveWorkbookByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WorkbookUsecaseInterface_RetrieveWorkbookByID_Call) RunAndReturn(run func(context.Context, *domain.OrganizationID, *domain.AppUserID, int) (*student.WorkbookRetrieveModel, error)) *WorkbookUsecaseInterface_RetrieveWorkbookByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewWorkbookUsecaseInterface creates a new instance of WorkbookUsecaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkbookUsecaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkbookUsecaseInterface {
	mock := &WorkbookUsecaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
