---
on:
  push:
    branches:
      - main
name: Build
jobs:
  test_go:
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3307
          mysql version: "5.7"
          mysql database: "testdb"
          mysql user: "user"
          mysql password: "password"

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        id: bazel_cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Check cache
        run: ${{ steps.bazel_cache.outputs.cache-hit }}

      - name: bazel
        run: bazel info

      - name: Test
        run: make test

      - name: Push
        run: make docker-push
